apiVersion: batch/v1
kind: CronJob
metadata:
  name: peloton-garmin-sync
spec:
  schedule: {{ .Values.config.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: peloton-garmin-sync
          labels:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: peloton-to-garmin-sa
          containers:
            - name: peloton-to-garmin
              image: {{ .Values.config.image | default "philosowaffle/peloton-to-garmin:stable" }}
              env:
                - name: TZ
                  value: {{ .Values.config.timezone | default "America/Los_Angeles" }}
              {{- if .Values.config.vaultEnabled }}
                - name: P2G_PELOTON__PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: peloton-to-garmin
                      key: peloton-password
                - name: P2G_GARMIN__PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: peloton-to-garmin
                      key: garmin-password
              {{- end }}
              volumeMounts:
                {{- if .Values.config.vaultEnabled }}
                - name: secrets-store-inline
                  mountPath: "/mnt/secrets-store"
                  readOnly: true
                {{- end }}
                - name: configmap
                  mountPath: "/app/configuration.local.json"
                  subPath: "configuration.local.json"
          volumes:
            - name: configmap
              configMap:
                name: peloton-garmin-configmap
            {{- if .Values.config.vaultEnabled }}
            - name: secrets-store-inline
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "vault-peloton-to-garmin"
            {{- end }}
          restartPolicy: OnFailure
